/*
 ============================================================================
 Name        : ultrasonic.h
 Author      : Aziza Zamel
 Description : Header file for the Ultrasonic Sensor Driver
 Date        : 8/10/2024
 ============================================================================
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* Buzzer HW Port and Pin Id */
#define ULTRASONIC_TRIG_PORT_ID		PORTD_ID
#define ULTRASONIC_TRIG_PIN_ID		PIN7_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/


/*
 * Description : Function to initialize the Ultrasonic sensor
 * 	1. Initialize the ICU driver as required.
 * 	2. Set up the ICU callback function.
 * 	3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Function responsible for Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Function responsible for:
 * 1. Send the trigger pulse by using the Ultrasonic_Trigger function.
 * 2. Start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
